./testAnalysis none 1 0
./testAnalysis none 1 1
./testAnalysis none 1 2
./testAnalysis none 1 10
./testAnalysis none 1 11
./testAnalysis none 1 12
./testAnalysis none 1 20
./testAnalysis none 1 21
./testAnalysis none 1 22
root -b -q check_Eff.C+\(\"testAnalysis_smear1_cond0.root\",\"0\"\)
root -b -q check_Eff.C+\(\"testAnalysis_smear1_cond1.root\",\"1\"\)
root -b -q check_Eff.C+\(\"testAnalysis_smear1_cond2.root\",\"2\"\)
root -b -q check_Eff.C+\(\"testAnalysis_smear1_cond10.root\",\"10\"\)
root -b -q check_Eff.C+\(\"testAnalysis_smear1_cond11.root\",\"11\"\)
root -b -q check_Eff.C+\(\"testAnalysis_smear1_cond12.root\",\"12\"\)
root -b -q check_Eff.C+\(\"testAnalysis_smear1_cond20.root\",\"20\"\)
root -b -q check_Eff.C+\(\"testAnalysis_smear1_cond21.root\",\"21\"\)
root -b -q check_Eff.C+\(\"testAnalysis_smear1_cond22.root\",\"22\"\)
